package com.darkndev.everkeep.utils.user_preferences

enum class RequestType {
    WRITE_EXTERNAL_STORAGE_PERMISSION,
    SCHEDULE_EXACT_ALARM_ENABLE,
    POST_NOTIFICATION_PERMISSION,
    NOTIFICATION_ENABLE,
    NOTIFICATION_CHANNEL_ENABLE,
    SHOW_ABOUT
}